import './globals.css';
import { Suspense } from 'react';
import PostHogProvider from '@/components/PostHogProvider';

export const metadata = {
  title: 'mylocaljam',
  description: 'Your local source, all in one spot.',
  keywords: 'live music, jersey shore, asbury park, belmar, point pleasant, concerts, events tonight, local bands, NJ music',
  openGraph: {
    title: 'Your local music source, all in one spot.',
    description: 'Your local music source, all in one spot.',
    url: 'https://mylocaljam.com',
    siteName: 'myLocaljam',
    // og:image is generated dynamically by src/app/opengraph-image.js
    // (Next.js auto-registers that file via the route convention). Don't
    // declare `images` here — explicit metadata overrides the convention.
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Your local music source, all in one spot.',
    description: 'Your local music source, all in one spot.',
    // twitter:image also auto-generated by the opengraph-image.js convention.
  },
  icons: {
    icon: '/favicon.ico',
    apple: '/apple-touch-icon.png',
  },
  other: {
    'theme-color': '#0D0D12',
    'mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-status-bar-style': 'black-translucent',
  },
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  viewportFit: 'cover',
  themeColor: '#0D0D12',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" prefix="og: http://ogp.me/ns#">
      <head>
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </head>
      <body>
        <Suspense fallback={null}>
          <PostHogProvider>
            {children}
          </PostHogProvider>
        </Suspense>
      </body>
    </html>
  );
}
